### ISSUE TITLE
Distinguishing between onMouseDown vs onClick for drag and drop

### ISSUE THREAD

**Issue by DaleSalcedo** [ntbosscher/react-window-sortable#2]
Hi there.  My list contains items that have buttons and inputs, so I need the onClick to work in conjunction with the onMouseClick event... but onClick is triggering the onMousedown event attached to the onSortMouseDown.

Is there any way to get the onSortMouseDown to work with a different event handler so that the user can click the different components of the item as well?  I tried attaching onSortMouseDown to onDrag and tried creating states to show if it was being dragged or not but I couldn't get anything to work.

The only solution is to make a drag handle like the example shows but I was hoping to not have to do that.;

**Comment by ntbosscher** [comment]
Hi @DaleSalcedo 
You should be able to do this by adding an `onMouseDown` and `onMouseUp` event handler on your button and calling `event.stopPropagation()` [mdn documentation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation)


e.g.
```jsx
<button 
   onClick={() => doStuff()} 
   onMouseDown={event => event.stopPropagation()} 
   onMouseUp={event => event.stopPropagation()} />
```

Hope that helps!

**Comment by DaleSalcedo** [comment]
nice it worked thank you!
