### ISSUE TITLE
List Blank while Scrolling even though I'm passing down the "style" prop

### ISSUE THREAD

**Issue by DaleSalcedo** [ntbosscher/react-window-sortable#3]
[react-window](https://imgur.com/a/xjh0eJl)
[react-window-sortable](https://imgur.com/a/oZBKrkD)

Literally my code doesn't change from switching from using:

import { FixedSizeList } from 'react-window';
to
import { SortableFixedSizeList } from 'react-window-sortable';

Any idea what could be causing the blanking?  Everything else works great and it's easy to use. I'd love to use this in a production project if this could be solved somehow!

**Comment by ntbosscher** [comment]
Hey @DaleSalcedo,

I can't think of anything off the top of my head... Could you make a codepen that reproduces the issue you're seeing?
It's hard to diagnose the problem if I don't have a way to reproduce it.

**Comment by DaleSalcedo** [comment]
Hey thanks for responding.. it's in production code so it's hard to share, we ended up just going with a different library because of it.  But appreciate the response and your willingness to help!

**Comment by DaleSalcedo** [comment]
I actually revisited this library and I removed a context menu library that was attached to each page which probably caused a bit heavier rendering which I think caused a bit more of the blanking out.  It works pretty well now.
