### ISSUE TITLE
'mouse down <#>' spamming console.

### ISSUE THREAD

**Issue by DaleSalcedo** [ntbosscher/react-window-sortable#4]
Is there any way we can get a prop setting for this maybe?  I'm sure it helps for debugging, but it spams the console which is a bit unnecessary in my opinion.

[https://imgur.com/a/GkOdecR](https://imgur.com/a/GkOdecR)

**Comment by DaleSalcedo** [comment]
I created a Pull Request on just removing the console.log incase it wasn't intentional to leave it in there.

**Comment by ntbosscher** [comment]
Merged #5
